Release 0.7.1 (#671)
* bump version

* revdepcheck run - No changes to commit

* Fix roxygen mistake found by CRAN incoming
Error: <gradientfill> is not recognized!

---------

Co-authored-by: GitHub Actions <actions@github.com>